services:
  client:
    image: jorotodorov/video-streaming-app-client:latest
    build:
      context: .
      dockerfile: ./client/Dockerfile
  server:
    image: jorotodorov/video-streaming-app-server:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_KEY: ${GOOGLE_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
