version: '3'
services:
  client:
    image: jorotodorov/video-streaming-app-client
    ports:
      - "3001:80"
  server:
    image: jorotodorov/video-streaming-app-server
    ports:
      - "3000:3000"
